---
title: "FinalAssignment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(tidyverse)
library(ggplot2)              
library(plotly)
```

## Loading the dataset
```{r}
unicef_indicator <- read.csv("unicef_indicator_2.csv")

plot <- ggplot(unicef_indicator, aes(x = time_period, y = obs_value, fill = region)) +
  geom_bar(stat = "identity") +
  labs(x = NULL, y = "% of children treated (< age 5)", title = "Treatment ") +
  guides(fill = FALSE)

plotly_plot <- ggplotly(plot)

plotly_plot
```

```{r pressure, echo=FALSE}
unicef_indicator <- read.csv("unicef_indicator_2.csv")
```
```{r}
plot <- ggplot(unicef_indicator, aes(x = time_period, y = obs_value)) +
  geom_bar(stat = "identity") +
  labs(x = NULL, y = "% of children treated (< age 5)", title = "Treatment ") +
  guides(fill = FALSE)
```
```{r}
plotly_plot <- ggplotly(plot)
plotly_plot
```
### Scatter Plot
```{r}
unicef_indicator <- read.csv("unicef_indicator_1.csv")
unicef_metadata <- read.csv("unicef_metadata1.csv")
=
unicef_join <- left_join(unicef_indicator, unicef_metadata, by="region")
=
ggplot(unicef_join, aes(x = life, y = obs_value)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Life Expectancy at birth", y = " Treatment", title = " Treatment vs. Life Expectancy")
```

```{r}
unicef_indicator <- read.csv("unicef_indicator_2.csv")
unicef_metadata <- read.csv("unicef_metadata1.csv")

unicef_ts_data <- ts(unicef_indicator$obs_value, start = c(2005), end = c(2021), frequency = 1)

plot(unicef_ts, type = "l", xlab = "Years", ylab = "% of children treated (< age 5)", 
     main = "Treatment of Diarrhoea Over Time")


```
```{r}
library(ggplot2)              
library(tidyverse)            
if (!require("mapdata")) install.packages("mapdata", dependencies = TRUE)
library(mapdata)

unicef_indicator <- read.csv("unicef_indicator_1.csv")
View(unicef_indicator)

mapdata <- map_data("world") 
View(mapdata)
mapdata <- left_join(mapdata, unicef_indicator, by="region")
View(mapdata)

mapData1<-ggplot(mapdata, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = obs_value), color = "grey")
mapData1

mapData2 <- mapData1 + scale_fill_gradient(name = "Diarrhoea treatment", low = "burlywood3", high =  "chocolate", na.value = "grey90")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
mapData2

if (!require("cowplot")) install.packages("cowplot", dependencies = TRUE)
library(cowplot)
if (!require("magick")) install.packages("magick", dependencies = TRUE)
library(magick)


ggdraw() +
  draw_plot(mapData2)


```


